import React from 'react';
import {observable, computed} from 'mobx';
import {guid} from '../AppState';
import bmcBlock from './bmcBlock';

// positioning of the blocks:
// we use a maximum screen width of 1024 pixels (768 x 1024 resolution)
// this is the native resolution of iPads and seems to be a reasonable
// resolution that most screens and beamers can reach.
// if we make our blocks 200px wide, they'll fit in 1000px. Leaving
// 12px left and right.
// if we use the height, we have 768px. 100px are for the menu, so
// this leaves 668. Use height of 220px.
export default class bmcModel {
    id;
    @observable title = 'Business Model Canvas';
    @observable blocks = [
        new bmcBlock('Key Partnerships',             12, 100, 200, 440,
<div>
    <p>Describe the suppliers and partners on which your company depends. 
        Partnerships can be created to reduce risk or to acquire resources.</p> 
    <ul>
        <li>Who are your partners and suppliers?</li> 
        <li>Which resources are acquired from them?</li> 
        <li>Which activities do partners perform?</li> 
    </ul>
</div>),
        new bmcBlock('Key Activities',          212, 100, 200, 220,
<div>
    <p>Define the most important activities your company must perform.</p> 
    <ul>
        <li>What activities are needed to maintain customer relationships? </li>
        <li>What activities are needed to generate value and revenue? </li>
        <li>What is needed to organise the distribution channels?</li>
    </ul>
</div>),
        new bmcBlock('Key Resources',           212, 320, 200, 220,
<div>
    <p>Describe the most important resources for your company. 
        Key resources can be physical, financial, intellectual, or human.</p> 
    <ul>
        <li>What resources are needed to create value or revenue? </li>
        <li>What resources does your company need to organise the distribution channels?</li> 
        <li>What resources are needed to maintain customer relationships?</li>
    </ul>
</div>),
        new bmcBlock('Value Proposition & Services',      412, 100, 200, 440,
<div>
    <p>Describe what value you create for your customers and users. 
        Also indicate the actual products or services that create value for your customers.</p>
    <ul> 
        <li>What customer problem or need do you solve?</li> 
        <li>Which products or services are offered?</li>
    </ul>
</div>),
        new bmcBlock('Customer Relationships',  612, 100, 200, 220,
<div>
    <p>Define which kind of relationships your company has with the customers. 
        Relationships can vary from personal to automated. </p>
    <ul>
        <li>How personal is the relationship with the customer?</li> 
        <li>What type of relationship does the customer expect?</li>  
    </ul>
</div>),
        new bmcBlock('Channels',                612, 320, 200, 220,
<div>
    <p>Describe how you reach your customers to deliver the value. </p>
    <ul>
        <li>How does your company reach customers?</li> 
        <li>Which communication, distribution and sales channels are used?</li> 
        <li>How would customers want to be reached? </li>
    </ul>
</div>),
        new bmcBlock('Customer Segments',       812, 100, 200, 440,
<div>
    <p>Define the different groups of people or organisations you aim to reach and serve. </p>
    <ul>
        <li>Who are the target customers? </li>
        <li>For whom are you creating value? </li>
        <li>Who are your most important customers?</li> 
    </ul>
</div>),
        new bmcBlock('Cost Structure',           12, 540, 500, 220,
<div>
    <p>Creating and delivering value to customers will result in costs. 
        Describe the most important costs inherent in your business model. </p>
    <ul>
        <li>Which Key Resources are most expensive?</li>
        <li>Which Key Activities are most expensive?</li>
    </ul>
</div>),
        new bmcBlock('Revenue Streams',         512, 540, 500, 220,
<div>
    <p>Describe how the company generates revenues. 
        Revenue is generated by selling your products or services or from other activities. </p>
    <ul>
        <li>For what are the customers willing to pay? </li>
        <li>For what are the customers currently paying? </li>
        <li>How do customers prefer to pay? </li>
    </ul>
</div>)
    ];
    // allow postits also outside of blocks
    @observable postIts = [];
    @observable x = 0;
    @observable y = 0;

    constructor( title ) {
        this.id = guid();
        this.title = title;
    }


}
